name: aconsia_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  animated_snack_bar: ^0.4.0
  cloud_firestore: ^5.6.7
  cloudinary_public: ^0.23.1
  colorful_safe_area: ^1.0.0
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  dio: ^5.4.2+1
  dropdown_button2: ^2.3.9
  file_picker: ^5.2.8
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.0
  image_compression: ^1.0.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  store_redirect: ^2.0.4
  syncfusion_flutter_pdfviewer: ^29.1.38
  toastification: ^3.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.5.0
  custom_lint: ^0.6.4
  dependency_validator: ^4.1.3
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/navbar/
    - .env

flutter_gen:
  output: lib/core/utils/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/images/img_rasa.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    # image_path: "assets/images/img_rasa.png"
    background_color: "#F4F2EC"
    theme_color: "#F4F2EC"
  windows:
    generate: true
    # image_path: "assets/images/img_rasa.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    # image_path: "assets/images/img_rasa.png"
